In [2]:
print("Hello Bhai")

Hello Bhai

In [3]:
pip install kaggle

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels
Requirement already satisfied: kaggle in /home/d829f3b6-9081-4968-932c-75d151c8981e/.local/lib/python3.12/site-packages (2.2.4)
Requirement already satisfied: bleach in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from kaggle) (6.3.0)
Requirement already satisfied: jupytext in /home/d829f3b6-9081-4968-932c-75d151c8981e/.local/lib/python3.12/site-packages (from kaggle) (1.19.5)
Requirement already satisfied: kagglesdk<1.0,>=0.1.35 in /home/d829f3b6-9081-4968-932c-75d151c8981e/.local/lib/python3.12/site-packages (from kaggle) (0.1.36)
Requirement already satisfied: packaging in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from kaggle) (25.0)
Requirement already satisfied: protobuf in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from kaggle) (5.29.3)
Requirement already satisfied: python-dateutil in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-dotenv in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from kaggle) (1.1.0)
Requirement already satisfied: python-slugify in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from kaggle) (2.32.5)
Requirement already satisfied: tqdm in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from kaggle) (2.6.0)
Requirement already satisfied: webencodings in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from jupytext->kaggle) (2.2.0)
Requirement already satisfied: mdit-py-plugins in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from jupytext->kaggle) (0.5.0)
Requirement already satisfied: nbformat in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: mdurl~=0.1 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from nbformat->jupytext->kaggle) (4.25.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from nbformat->jupytext->kaggle) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.28.0)
Requirement already satisfied: platformdirs>=2.5 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.5.0)
Requirement already satisfied: typing-extensions>=4.4.0 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat->jupytext->kaggle) (4.15.0)
Requirement already satisfied: six>=1.5 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from requests->kaggle) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from requests->kaggle) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from requests->kaggle) (2025.11.12)
Note: you may need to restart the kernel to use updated packages.

In [4]:
pip list

Package                           Version
--------------------------------- --------------------
aiobotocore                       2.25.0
aiodns                            3.5.0
aiohappyeyeballs                  2.6.1
aiohttp                           3.13.2
aioitertools                      0.12.0
aiosignal                         1.4.0
alabaster                         1.0.0
altair                            5.5.0
anaconda-anon-usage               0.7.5
anaconda-auth                     0.12.0
anaconda-catalogs                 0.2.0
anaconda-cli-base                 0.7.0
anaconda-cloud-storage            0.3.3
annotated-types                   0.6.0
anyio                             4.10.0
appdirs                           1.4.4
argon2-cffi                       21.3.0
argon2-cffi-bindings              25.1.0
arrow                             1.4.0
astroid                           3.3.11
astropy                           7.1.1
astropy-iers-data                 0.2025.11.24.0.39.11
asttokens                         3.0.0
async-lru                         2.0.5
asyncssh                          2.21.1
atomicwrites                      1.4.0
attrs                             25.4.0
Automat                           24.8.1
autopep8                          2.0.4
babel                             2.17.0
bcrypt                            5.0.0
beautifulsoup4                    4.14.2
binaryornot                       0.4.4
black                             25.11.0
bleach                            6.3.0
blinker                           1.9.0
bokeh                             3.4.0
botocore                          1.40.46
Bottleneck                        1.4.2
brotlicffi                        1.2.0.0
cachetools                        6.2.2
cattrs                            25.3.0
certifi                           2025.11.12
cffi                              2.0.0
cfgv                              3.5.0
chardet                           5.2.0
charset-normalizer                3.4.4
click                             8.2.1
cloudpickle                       3.1.2
colorcet                          3.1.0
comm                              0.2.3
commonmark                        0.9.1
constantly                        23.10.4
contourpy                         1.3.3
cookiecutter                      2.6.0
cryptography                      46.0.3
cssselect                         1.2.0
cycler                            0.11.0
dask                              2025.11.0
datashader                        0.16.0
debugpy                           1.8.16
decorator                         5.2.1
defusedxml                        0.7.1
diff-match-patch                  20200713
dill                              0.4.0
distlib                           0.4.0
distributed                       2025.11.0
docstring-to-markdown             0.17
docutils                          0.21.2
et_xmlfile                        2.0.0
executing                         2.2.1
fastjsonschema                    2.21.2
filelock                          3.20.0
flake8                            7.1.1
Flask                             3.1.2
fonttools                         4.60.1
frozenlist                        1.8.0
fsspec                            2025.10.0
future                            1.0.0
gitdb                             4.0.12
GitPython                         3.1.45
gmpy2                             2.2.2
greenlet                          3.2.4
h11                               0.16.0
h5py                              3.15.1
HeapDict                          1.0.1
holoviews                         1.18.3
html5lib                          1.1
httpcore                          1.0.9
httpx                             0.28.1
hvplot                            0.9.2
hyperlink                         21.0.0
identify                          2.5.5
idna                              3.11
ImageIO                           2.37.2
imagesize                         1.4.1
imbalanced-learn                  0.14.0
importlib_metadata                8.7.0
incremental                       24.7.2
inflection                        0.5.1
iniconfig                         2.1.0
intake                            2.0.8
intervaltree                      3.1.0
ipykernel                         6.31.0
ipympl                            0.9.7
ipython                           9.7.0
ipython_pygments_lexers           1.1.1
ipywidgets                        8.1.7
isort                             6.1.0
itemadapter                       0.12.1
itemloaders                       1.3.2
itsdangerous                      2.2.0
jaraco.classes                    3.4.0
jaraco.context                    0.0.0
jaraco.functools                  4.1.0
jedi                              0.19.2
jeepney                           0.7.1
jellyfish                         1.2.1
Jinja2                            3.1.6
jmespath                          1.0.1
joblib                            1.5.2
json5                             0.12.1
jsonschema                        4.25.0
jsonschema-specifications         2025.9.1
jupyter                           1.1.1
jupyter_client                    8.6.3
jupyter-console                   6.6.3
jupyter_core                      5.9.1
jupyter-events                    0.12.0
jupyter-lsp                       2.2.5
jupyter_server                    2.17.0
jupyter_server_terminals          0.5.3
jupyterlab                        4.5.0
jupyterlab_pygments               0.3.0
jupyterlab_server                 2.28.0
jupyterlab_widgets                3.0.15
jupytext                          1.19.5
kaggle                            2.2.4
kagglesdk                         0.1.36
keyring                           25.7.0
kiwisolver                        1.4.9
lazy_loader                       0.4
lckr_jupyterlab_variableinspector 3.2.4
linkify-it-py                     2.0.3
llvmlite                          0.45.1
lmdb                              1.7.5
locket                            1.0.0
lsprotocol                        2025.0.0
lxml                              5.3.0
lz4                               4.4.5
Markdown                          3.8
markdown-it-py                    2.2.0
MarkupSafe                        3.0.2
matplotlib                        3.10.6
matplotlib-inline                 0.2.1
mccabe                            0.7.0
mdit-py-plugins                   0.5.0
mdurl                             0.1.2
mistune                           3.1.2
mkl_fft                           2.1.1
mkl_random                        1.3.0
mkl-service                       2.5.2
more-itertools                    10.8.0
mpi4py                            4.0.3
mpmath                            1.3.0
msgpack                           1.1.1
multidict                         6.7.0
multipledispatch                  1.0.0
mypy                              1.17.1
mypy-extensions                   1.0.0
narwhals                          2.7.0
nbclient                          0.10.2
nbconvert                         7.16.6
nbformat                          5.10.4
nest-asyncio                      1.6.0
networkx                          3.5
nltk                              3.9.2
nodeenv                           1.9.1
notebook                          7.5.0
notebook_shim                     0.2.4
numba                             0.62.1
numexpr                           2.14.1
numpy                             1.26.4
numpydoc                          1.9.0
openpyxl                          3.1.5
packaging                         25.0
pandas                            2.3.3
pandocfilters                     1.5.1
panel                             1.4.1
param                             2.1.0
parsel                            1.10.0
parso                             0.8.5
partd                             1.4.2
pathlib_abc                       0.5.2
pathspec                          0.12.1
patsy                             1.0.1
pexpect                           4.9.0
pickleshare                       0.7.5
pillow                            12.0.0
pip                               25.3
pkce                              1.0.3
platformdirs                      4.5.0
plotly                            6.5.0
pluggy                            1.5.0
pre-commit                        3.4.0
prometheus_client                 0.21.1
prompt_toolkit                    3.0.52
propcache                         0.3.1
Protego                           0.4.0
protobuf                          5.29.3
psutil                            7.0.0
psycopg2-binary                   2.9.12
ptyprocess                        0.7.0
pure_eval                         0.2.3
py-cpuinfo                        9.0.0
pyarrow                           21.0.0
pyasn1                            0.6.1
pyasn1_modules                    0.4.2
pycares                           4.10.0
pycodestyle                       2.12.1
pycparser                         2.23
pyct                              0.6.0
pycurl                            7.45.7
pydantic                          2.12.4
pydantic_core                     2.41.5
pydantic-settings                 2.12.0
PyDispatcher                      2.0.7
pydocstyle                        6.3.0
pyerfa                            2.0.1.5
pyflakes                          3.2.0
PyGithub                          2.8.1
Pygments                          2.19.2
PyJWT                             2.10.1
pylint                            3.3.8
pylint-venv                       3.0.3
pyls-spyder                       0.4.0
PyMySQL                           1.2.0
PyNaCl                            1.6.0
pyodbc                            5.3.0
pyOpenSSL                         25.3.0
pyparsing                         3.2.5
PyQt5                             5.15.11
PyQt5_sip                         12.17.0
PyQtWebEngine                     5.15.7
PySocks                           1.7.1
pytest                            8.4.2
python-dateutil                   2.9.0.post0
python-dotenv                     1.1.0
python-json-logger                4.0.0
python-lsp-black                  2.0.0
python-lsp-jsonrpc                1.1.2
python-lsp-ruff                   2.3.0
python-lsp-server                 1.13.1
python-slugify                    8.0.4
pytokens                          0.3.0
pytoolconfig                      1.2.6
pytz                              2025.2
pyuca                             1.2
pyviz_comms                       3.0.6
PyWavelets                        1.9.0
pyxdg                             0.28
PyYAML                            6.0.3
pyzmq                             27.1.0
QDarkStyle                        3.2.3
qstylizer                         0.2.2
QtAwesome                         1.4.0
qtconsole                         5.7.0
QtPy                              2.4.3
queuelib                          1.8.0
readchar                          4.2.1
referencing                       0.37.0
regex                             2025.9.1
requests                          2.32.5
requests-file                     2.1.0
rfc3339-validator                 0.1.4
rfc3986-validator                 0.1.1
rich                              12.6.0
rich-cli                          1.8.1
rich-rst                          1.3.2
roman-numerals-py                 3.1.0
rope                              1.14.0
rpds-py                           0.28.0
rtree                             1.4.1
ruff                              0.12.0
s3fs                              2025.10.0
scikit-image                      0.25.2
scikit-learn                      1.7.2
scipy                             1.16.3
Scrapy                            2.13.4
seaborn                           0.13.2
SecretStorage                     3.4.0
semver                            3.0.4
Send2Trash                        1.8.2
service-identity                  24.2.0
setuptools                        80.9.0
shellingham                       1.5.4
sip                               6.12.0
six                               1.17.0
smmap                             5.0.2
sniffio                           1.3.1
snowballstemmer                   3.0.1
sortedcontainers                  2.4.0
soupsieve                         2.5
Sphinx                            8.2.3
sphinxcontrib-applehelp           2.0.0
sphinxcontrib-devhelp             2.0.0
sphinxcontrib-htmlhelp            2.1.0
sphinxcontrib-jsmath              1.0.1
sphinxcontrib-qthelp              2.0.0
sphinxcontrib-serializinghtml     2.0.0
spyder                            6.1.0
spyder-kernels                    3.1.2
SQLAlchemy                        2.0.43
stack_data                        0.6.3
statsmodels                       0.14.5
streamlit                         1.52.1
superqt                           0.7.6
sympy                             1.14.0
tables                            3.10.2
tabulate                          0.9.0
tblib                             3.1.0
tenacity                          9.1.2
terminado                         0.18.1
text-unidecode                    1.3
textdistance                      4.6.3
textual                           0.1.18
threadpoolctl                     3.5.0
three-merge                       0.1.1
tifffile                          2025.10.4
tinycss2                          1.4.0
tldextract                        5.1.2
toml                              0.10.2
tomli                             2.2.1
tomlkit                           0.13.3
toolz                             1.1.0
tornado                           6.5.1
tqdm                              4.67.1
traitlets                         5.14.3
Twisted                           25.5.0
typer                             0.17.4
typing_extensions                 4.15.0
typing-inspection                 0.4.2
tzdata                            2025.2
uc-micro-py                       1.0.3
ujson                             5.11.0
ukkonen                           1.0.1
universal_pathlib                 0.3.7
urllib3                           2.6.0
uvloop                            0.22.1
virtualenv                        20.28.0
w3lib                             2.3.1
watchdog                          6.0.0
wcwidth                           0.2.13
webencodings                      0.5.1
websocket-client                  1.8.0
Werkzeug                          3.1.3
whatthepatch                      1.0.7
wheel                             0.45.1
widgetsnbextension                4.0.14
wrapt                             1.17.0
wurlitzer                         3.1.1
xarray                            2025.10.1
xyzservices                       2025.4.0
yapf                              0.43.0
yarl                              1.22.0
zict                              3.0.0
zipp                              3.23.0
zope.interface                    8.0.1
Note: you may need to restart the kernel to use updated packages.

In [5]:
!kaggle datasets download -d najir0123/walmart-10k-sales-datasets

/bin/bash: kaggle: command not found

In [6]:
!mkdir -p ~/.kaggle && echo KGAT_3069bdcf3d42387179e6acb68ffde48a > ~/.kaggle/access_token && chmod 600 ~/.kaggle/access_token

In [7]:
!pip install kaggle

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels
Requirement already satisfied: kaggle in /home/d829f3b6-9081-4968-932c-75d151c8981e/.local/lib/python3.12/site-packages (2.2.4)
Requirement already satisfied: bleach in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from kaggle) (6.3.0)
Requirement already satisfied: jupytext in /home/d829f3b6-9081-4968-932c-75d151c8981e/.local/lib/python3.12/site-packages (from kaggle) (1.19.5)
Requirement already satisfied: kagglesdk<1.0,>=0.1.35 in /home/d829f3b6-9081-4968-932c-75d151c8981e/.local/lib/python3.12/site-packages (from kaggle) (0.1.36)
Requirement already satisfied: packaging in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from kaggle) (25.0)
Requirement already satisfied: protobuf in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from kaggle) (5.29.3)
Requirement already satisfied: python-dateutil in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-dotenv in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from kaggle) (1.1.0)
Requirement already satisfied: python-slugify in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from kaggle) (2.32.5)
Requirement already satisfied: tqdm in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from kaggle) (2.6.0)
Requirement already satisfied: webencodings in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from jupytext->kaggle) (2.2.0)
Requirement already satisfied: mdit-py-plugins in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from jupytext->kaggle) (0.5.0)
Requirement already satisfied: nbformat in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: mdurl~=0.1 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from nbformat->jupytext->kaggle) (4.25.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from nbformat->jupytext->kaggle) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.28.0)
Requirement already satisfied: platformdirs>=2.5 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.5.0)
Requirement already satisfied: typing-extensions>=4.4.0 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat->jupytext->kaggle) (4.15.0)
Requirement already satisfied: six>=1.5 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from requests->kaggle) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from requests->kaggle) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from requests->kaggle) (2025.11.12)

In [8]:
!kaggle datasets download -d najir0123/walmart-10k-sales-datasets

/bin/bash: kaggle: command not found

In [9]:
!python -m kaggle datasets download -d najir0123/walmart-10k-sales-datasets

Traceback (most recent call last):
  File "/opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages/urllib3/connectionpool.py", line 773, in urlopen
    self._prepare_proxy(conn)
  File "/opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1042, in _prepare_proxy
    conn.connect()
  File "/opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages/urllib3/connection.py", line 776, in connect
    self._tunnel()
  File "/opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/http/client.py", line 981, in _tunnel
    raise OSError(f"Tunnel connection failed: {code} {message.strip()}")
OSError: Tunnel connection failed: 403 Forbidden

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', OSError('Tunnel connection failed: 403 Forbidden'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages/requests/adapters.py", line 644, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.kaggle.com', port=443): Max retries exceeded with url: /v1/security.OAuthService/IntrospectToken (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 403 Forbidden')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/d829f3b6-9081-4968-932c-75d151c8981e/.local/lib/python3.12/site-packages/kaggle/__main__.py", line 11, in <module>
    main()
  File "/home/d829f3b6-9081-4968-932c-75d151c8981e/.local/lib/python3.12/site-packages/kaggle/cli.py", line 75, in main
    api.authenticate()
  File "/home/d829f3b6-9081-4968-932c-75d151c8981e/.local/lib/python3.12/site-packages/kaggle/api/kaggle_api_extended.py", line 1239, in authenticate
    if self._authenticate_with_access_token():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/d829f3b6-9081-4968-932c-75d151c8981e/.local/lib/python3.12/site-packages/kaggle/api/kaggle_api_extended.py", line 1310, in _authenticate_with_access_token
    username = self._introspect_token(access_token)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/d829f3b6-9081-4968-932c-75d151c8981e/.local/lib/python3.12/site-packages/kaggle/api/kaggle_api_extended.py", line 1352, in _introspect_token
    response = kaggle.security.oauth_client.introspect_token(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/d829f3b6-9081-4968-932c-75d151c8981e/.local/lib/python3.12/site-packages/kagglesdk/security/services/oauth_service.py", line 44, in introspect_token
    return self._client.call("security.OAuthService", "IntrospectToken", request, IntrospectTokenResponse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/d829f3b6-9081-4968-932c-75d151c8981e/.local/lib/python3.12/site-packages/kagglesdk/kaggle_http_client.py", line 104, in call
    http_response = self._session.send(http_request, **settings)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages/requests/adapters.py", line 671, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='api.kaggle.com', port=443): Max retries exceeded with url: /v1/security.OAuthService/IntrospectToken (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 403 Forbidden')))

In [10]:
!kaggle datasets download -d najir0123/walmart-10k-sales-datasets

/bin/bash: kaggle: command not found

In [11]:
import sys
!{sys.executable} -m pip install kaggle

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels
Requirement already satisfied: kaggle in /home/d829f3b6-9081-4968-932c-75d151c8981e/.local/lib/python3.12/site-packages (2.2.4)
Requirement already satisfied: bleach in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from kaggle) (6.3.0)
Requirement already satisfied: jupytext in /home/d829f3b6-9081-4968-932c-75d151c8981e/.local/lib/python3.12/site-packages (from kaggle) (1.19.5)
Requirement already satisfied: kagglesdk<1.0,>=0.1.35 in /home/d829f3b6-9081-4968-932c-75d151c8981e/.local/lib/python3.12/site-packages (from kaggle) (0.1.36)
Requirement already satisfied: packaging in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from kaggle) (25.0)
Requirement already satisfied: protobuf in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from kaggle) (5.29.3)
Requirement already satisfied: python-dateutil in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-dotenv in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from kaggle) (1.1.0)
Requirement already satisfied: python-slugify in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from kaggle) (2.32.5)
Requirement already satisfied: tqdm in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from kaggle) (2.6.0)
Requirement already satisfied: webencodings in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from jupytext->kaggle) (2.2.0)
Requirement already satisfied: mdit-py-plugins in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from jupytext->kaggle) (0.5.0)
Requirement already satisfied: nbformat in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: mdurl~=0.1 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from nbformat->jupytext->kaggle) (4.25.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from nbformat->jupytext->kaggle) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.28.0)
Requirement already satisfied: platformdirs>=2.5 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.5.0)
Requirement already satisfied: typing-extensions>=4.4.0 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat->jupytext->kaggle) (4.15.0)
Requirement already satisfied: six>=1.5 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from requests->kaggle) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from requests->kaggle) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from requests->kaggle) (2025.11.12)

In [12]:
!{sys.executable} -m kaggle datasets download -d najir0123/walmart-10k-sales-datasets

Traceback (most recent call last):
  File "/opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages/urllib3/connectionpool.py", line 773, in urlopen
    self._prepare_proxy(conn)
  File "/opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1042, in _prepare_proxy
    conn.connect()
  File "/opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages/urllib3/connection.py", line 776, in connect
    self._tunnel()
  File "/opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/http/client.py", line 981, in _tunnel
    raise OSError(f"Tunnel connection failed: {code} {message.strip()}")
OSError: Tunnel connection failed: 403 Forbidden

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', OSError('Tunnel connection failed: 403 Forbidden'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages/requests/adapters.py", line 644, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.kaggle.com', port=443): Max retries exceeded with url: /v1/security.OAuthService/IntrospectToken (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 403 Forbidden')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/d829f3b6-9081-4968-932c-75d151c8981e/.local/lib/python3.12/site-packages/kaggle/__main__.py", line 11, in <module>
    main()
  File "/home/d829f3b6-9081-4968-932c-75d151c8981e/.local/lib/python3.12/site-packages/kaggle/cli.py", line 75, in main
    api.authenticate()
  File "/home/d829f3b6-9081-4968-932c-75d151c8981e/.local/lib/python3.12/site-packages/kaggle/api/kaggle_api_extended.py", line 1239, in authenticate
    if self._authenticate_with_access_token():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/d829f3b6-9081-4968-932c-75d151c8981e/.local/lib/python3.12/site-packages/kaggle/api/kaggle_api_extended.py", line 1310, in _authenticate_with_access_token
    username = self._introspect_token(access_token)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/d829f3b6-9081-4968-932c-75d151c8981e/.local/lib/python3.12/site-packages/kaggle/api/kaggle_api_extended.py", line 1352, in _introspect_token
    response = kaggle.security.oauth_client.introspect_token(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/d829f3b6-9081-4968-932c-75d151c8981e/.local/lib/python3.12/site-packages/kagglesdk/security/services/oauth_service.py", line 44, in introspect_token
    return self._client.call("security.OAuthService", "IntrospectToken", request, IntrospectTokenResponse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/d829f3b6-9081-4968-932c-75d151c8981e/.local/lib/python3.12/site-packages/kagglesdk/kaggle_http_client.py", line 104, in call
    http_response = self._session.send(http_request, **settings)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages/requests/adapters.py", line 671, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='api.kaggle.com', port=443): Max retries exceeded with url: /v1/security.OAuthService/IntrospectToken (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 403 Forbidden')))

In [13]:
!{sys.executable} -m pip show kaggle

Name: kaggle
Version: 2.2.4
Summary: Access Kaggle resources anywhere
Home-page: https://github.com/Kaggle/kaggle-cli
Author:
Author-email: Kaggle <support@kaggle.com>
License: Apache License
                           Version 2.0, January 2004
                        http://www.apache.org/licenses/

   TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION

   1. Definitions.

      "License" shall mean the terms and conditions for use, reproduction,
      and distribution as defined by Sections 1 through 9 of this document.

      "Licensor" shall mean the copyright owner or entity authorized by
      the copyright owner that is granting the License.

      "Legal Entity" shall mean the union of the acting entity and all
      other entities that control, are controlled by, or are under common
      control with that entity. For the purposes of this definition,
      "control" means (i) the power, direct or indirect, to cause the
      direction or management of such entity, whether by contract or
      otherwise, or (ii) ownership of fifty percent (50%) or more of the
      outstanding shares, or (iii) beneficial ownership of such entity.

      "You" (or "Your") shall mean an individual or Legal Entity
      exercising permissions granted by this License.

      "Source" form shall mean the preferred form for making modifications,
      including but not limited to software source code, documentation
      source, and configuration files.

      "Object" form shall mean any form resulting from mechanical
      transformation or translation of a Source form, including but
      not limited to compiled object code, generated documentation,
      and conversions to other media types.

      "Work" shall mean the work of authorship, whether in Source or
      Object form, made available under the License, as indicated by a
      copyright notice that is included in or attached to the work
      (an example is provided in the Appendix below).

      "Derivative Works" shall mean any work, whether in Source or Object
      form, that is based on (or derived from) the Work and for which the
      editorial revisions, annotations, elaborations, or other modifications
      represent, as a whole, an original work of authorship. For the purposes
      of this License, Derivative Works shall not include works that remain
      separable from, or merely link (or bind by name) to the interfaces of,
      the Work and Derivative Works thereof.

      "Contribution" shall mean any work of authorship, including
      the original version of the Work and any modifications or additions
      to that Work or Derivative Works thereof, that is intentionally
      submitted to Licensor for inclusion in the Work by the copyright owner
      or by an individual or Legal Entity authorized to submit on behalf of
      the copyright owner. For the purposes of this definition, "submitted"
      means any form of electronic, verbal, or written communication sent
      to the Licensor or its representatives, including but not limited to
      communication on electronic mailing lists, source code control systems,
      and issue tracking systems that are managed by, or on behalf of, the
      Licensor for the purpose of discussing and improving the Work, but
      excluding communication that is conspicuously marked or otherwise
      designated in writing by the copyright owner as "Not a Contribution."

      "Contributor" shall mean Licensor and any individual or Legal Entity
      on behalf of whom a Contribution has been received by Licensor and
      subsequently incorporated within the Work.

   2. Grant of Copyright License. Subject to the terms and conditions of
      this License, each Contributor hereby grants to You a perpetual,
      worldwide, non-exclusive, no-charge, royalty-free, irrevocable
      copyright license to reproduce, prepare Derivative Works of,
      publicly display, publicly perform, sublicense, and distribute the
      Work and such Derivative Works in Source or Object form.

   3. Grant of Patent License. Subject to the terms and conditions of
      this License, each Contributor hereby grants to You a perpetual,
      worldwide, non-exclusive, no-charge, royalty-free, irrevocable
      (except as stated in this section) patent license to make, have made,
      use, offer to sell, sell, import, and otherwise transfer the Work,
      where such license applies only to those patent claims licensable
      by such Contributor that are necessarily infringed by their
      Contribution(s) alone or by combination of their Contribution(s)
      with the Work to which such Contribution(s) was submitted. If You
      institute patent litigation against any entity (including a
      cross-claim or counterclaim in a lawsuit) alleging that the Work
      or a Contribution incorporated within the Work constitutes direct
      or contributory patent infringement, then any patent licenses
      granted to You under this License for that Work shall terminate
      as of the date such litigation is filed.

   4. Redistribution. You may reproduce and distribute copies of the
      Work or Derivative Works thereof in any medium, with or without
      modifications, and in Source or Object form, provided that You
      meet the following conditions:

      (a) You must give any other recipients of the Work or
          Derivative Works a copy of this License; and

      (b) You must cause any modified files to carry prominent notices
          stating that You changed the files; and

      (c) You must retain, in the Source form of any Derivative Works
          that You distribute, all copyright, patent, trademark, and
          attribution notices from the Source form of the Work,
          excluding those notices that do not pertain to any part of
          the Derivative Works; and

      (d) If the Work includes a "NOTICE" text file as part of its
          distribution, then any Derivative Works that You distribute must
          include a readable copy of the attribution notices contained
          within such NOTICE file, excluding those notices that do not
          pertain to any part of the Derivative Works, in at least one
          of the following places: within a NOTICE text file distributed
          as part of the Derivative Works; within the Source form or
          documentation, if provided along with the Derivative Works; or,
          within a display generated by the Derivative Works, if and
          wherever such third-party notices normally appear. The contents
          of the NOTICE file are for informational purposes only and
          do not modify the License. You may add Your own attribution
          notices within Derivative Works that You distribute, alongside
          or as an addendum to the NOTICE text from the Work, provided
          that such additional attribution notices cannot be construed
          as modifying the License.

      You may add Your own copyright statement to Your modifications and
      may provide additional or different license terms and conditions
      for use, reproduction, or distribution of Your modifications, or
      for any such Derivative Works as a whole, provided Your use,
      reproduction, and distribution of the Work otherwise complies with
      the conditions stated in this License.

   5. Submission of Contributions. Unless You explicitly state otherwise,
      any Contribution intentionally submitted for inclusion in the Work
      by You to the Licensor shall be under the terms and conditions of
      this License, without any additional terms or conditions.
      Notwithstanding the above, nothing herein shall supersede or modify
      the terms of any separate license agreement you may have executed
      with Licensor regarding such Contributions.

   6. Trademarks. This License does not grant permission to use the trade
      names, trademarks, service marks, or product names of the Licensor,
      except as required for reasonable and customary use in describing the
      origin of the Work and reproducing the content of the NOTICE file.

   7. Disclaimer of Warranty. Unless required by applicable law or
      agreed to in writing, Licensor provides the Work (and each
      Contributor provides its Contributions) on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
      implied, including, without limitation, any warranties or conditions
      of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A
      PARTICULAR PURPOSE. You are solely responsible for determining the
      appropriateness of using or redistributing the Work and assume any
      risks associated with Your exercise of permissions under this License.

   8. Limitation of Liability. In no event and under no legal theory,
      whether in tort (including negligence), contract, or otherwise,
      unless required by applicable law (such as deliberate and grossly
      negligent acts) or agreed to in writing, shall any Contributor be
      liable to You for damages, including any direct, indirect, special,
      incidental, or consequential damages of any character arising as a
      result of this License or out of the use or inability to use the
      Work (including but not limited to damages for loss of goodwill,
      work stoppage, computer failure or malfunction, or any and all
      other commercial damages or losses), even if such Contributor
      has been advised of the possibility of such damages.

   9. Accepting Warranty or Additional Liability. While redistributing
      the Work or Derivative Works thereof, You may choose to offer,
      and charge a fee for, acceptance of support, warranty, indemnity,
      or other liability obligations and/or rights consistent with this
      License. However, in accepting such obligations, You may act only
      on Your own behalf and on Your sole responsibility, not on behalf
      of any other Contributor, and only if You agree to indemnify,
      defend, and hold each Contributor harmless for any liability
      incurred by, or claims asserted against, such Contributor by reason
      of your accepting any such warranty or additional liability.

   END OF TERMS AND CONDITIONS

   APPENDIX: How to apply the Apache License to your work.

      To apply the Apache License to your work, attach the following
      boilerplate notice, with the fields enclosed by brackets "[]"
      replaced with your own identifying information. (Don't include
      the brackets!)  The text should be enclosed in the appropriate
      comment syntax for the file format. We also recommend that a
      file or class name and description of purpose be included on the
      same "printed page" as the copyright notice for easier
      identification within third-party archives.

   Copyright 2018 Kaggle Inc

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
Location: /home/d829f3b6-9081-4968-932c-75d151c8981e/.local/lib/python3.12/site-packages
Requires: bleach, jupytext, kagglesdk, packaging, protobuf, python-dateutil, python-dotenv, python-slugify, requests, tqdm, urllib3
Required-by:

In [14]:
import sys
!{sys.executable} -m zipfile -e walmart-10k-sales-datasets.zip .

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/zipfile/__main__.py", line 4, in <module>
    main()
  File "/opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/zipfile/__init__.py", line 2302, in main
    with ZipFile(src, 'r', metadata_encoding=encoding) as zf:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/zipfile/__init__.py", line 1352, in __init__
    self.fp = io.open(file, filemode)
              ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'walmart-10k-sales-datasets.zip'

In [15]:
!ls

 Customer_shopping_behavious_analysis.ipynb  'Walmart Sales .ipynb'
 Untitled.ipynb				      Walmart.csv
 Untitled1.ipynb			      customer_behavior.db
 Untitled2.ipynb			      customer_shopping_behavior.csv
 Untitled3.ipynb			      numpy.ipynb

In [16]:
import pandas as pd

In [17]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/najirh/Walmart_SQL_Python/main/Walmart.csv")
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [18]:
df.info

<bound method DataFrame.info of        invoice_id   Branch         City                category unit_price  \
0               1  WALM003  San Antonio       Health and beauty     $74.69
1               2  WALM048    Harlingen  Electronic accessories     $15.28
2               3  WALM067  Haltom City      Home and lifestyle     $46.33
3               4  WALM064      Bedford       Health and beauty     $58.22
4               5  WALM013       Irving       Sports and travel     $86.31
...           ...      ...          ...                     ...        ...
10046        9996  WALM056      Rowlett     Fashion accessories        $37
10047        9997  WALM030   Richardson      Home and lifestyle        $58
10048        9998  WALM050     Victoria     Fashion accessories        $52
10049        9999  WALM032        Tyler      Home and lifestyle        $79
10050       10000  WALM069     Rockwall     Fashion accessories        $62

       quantity      date      time payment_method  rating  profit_margin
0           7.0  05/01/19  13:08:00        Ewallet     9.1           0.48
1           5.0  08/03/19  10:29:00           Cash     9.6           0.48
2           7.0  03/03/19  13:23:00    Credit card     7.4           0.33
3           8.0  27/01/19  20:33:00        Ewallet     8.4           0.33
4           7.0  08/02/19  10:37:00        Ewallet     5.3           0.48
...         ...       ...       ...            ...     ...            ...
10046       3.0  03/08/23  10:10:00           Cash     3.0           0.33
10047       2.0  22/02/21  14:20:00           Cash     7.0           0.48
10048       3.0  15/06/23  16:00:00    Credit card     4.0           0.48
10049       2.0  25/02/21  12:25:00           Cash     7.0           0.48
10050       3.0  26/09/20   9:48:00           Cash     3.0           0.33

[10051 rows x 11 columns]>

In [19]:
import pandas as pd
df = pd.read_csv("Walmart.csv") 
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [20]:
import pandas as pd

In [21]:
print(pd.__version__)

2.3.3

In [22]:
df = pd.read_csv('Walmart.csv', encoding_errors = 'ignore')
df.shape

(10051, 11)

In [23]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [24]:
df.describe()

         invoice_id      quantity        rating  profit_margin
count  10051.000000  10020.000000  10051.000000   10051.000000
mean    5025.741220      2.353493      5.825659       0.393791
std     2901.174372      1.602658      1.763991       0.090669
min        1.000000      1.000000      3.000000       0.180000
25%     2513.500000      1.000000      4.000000       0.330000
50%     5026.000000      2.000000      6.000000       0.330000
75%     7538.500000      3.000000      7.000000       0.480000
max    10000.000000     10.000000     10.000000       0.570000

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   Branch          10051 non-null  object
 2   City            10051 non-null  object
 3   category        10051 non-null  object
 4   unit_price      10020 non-null  object
 5   quantity        10020 non-null  float64
 6   date            10051 non-null  object
 7   time            10051 non-null  object
 8   payment_method  10051 non-null  object
 9   rating          10051 non-null  float64
 10  profit_margin   10051 non-null  float64
dtypes: float64(3), int64(1), object(7)
memory usage: 863.9+ KB

In [26]:
df.duplicated().sum()

51

In [27]:
df.isnull().sum()

invoice_id         0
Branch             0
City               0
category           0
unit_price        31
quantity          31
date               0
time               0
payment_method     0
rating             0
profit_margin      0
dtype: int64

In [28]:
df.drop_duplicates(inplace=True)
df.duplicated().sum()

0

In [29]:
df.shape

(10000, 11)

In [30]:
df.dropna(inplace=True)

In [31]:
df.isnull().sum()

invoice_id        0
Branch            0
City              0
category          0
unit_price        0
quantity          0
date              0
time              0
payment_method    0
rating            0
profit_margin     0
dtype: int64

In [32]:
df.shape

(9969, 11)

In [35]:
df['unit_price']= df['unit_price'].str.replace('$' ,' ').astype(float)

In [37]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9969 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      9969 non-null   int64
 1   Branch          9969 non-null   object
 2   City            9969 non-null   object
 3   category        9969 non-null   object
 4   unit_price      9969 non-null   float64
 5   quantity        9969 non-null   float64
 6   date            9969 non-null   object
 7   time            9969 non-null   object
 8   payment_method  9969 non-null   object
 9   rating          9969 non-null   float64
 10  profit_margin   9969 non-null   float64
dtypes: float64(4), int64(1), object(6)
memory usage: 934.6+ KB

In [39]:
df.columns

Index(['invoice_id', 'Branch', 'City', 'category', 'unit_price', 'quantity',
       'date', 'time', 'payment_method', 'rating', 'profit_margin'],
      dtype='object')

In [40]:
df['total'] = df['unit_price']* df['quantity']

In [42]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin,total
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48,522.83
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48,76.40
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33,324.31
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33,465.76
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48,604.17

In [43]:
df.columns = df.columns.str.lower()

In [45]:
df.columns

Index(['invoice_id', 'branch', 'city', 'category', 'unit_price', 'quantity',
       'date', 'time', 'payment_method', 'rating', 'profit_margin', 'total'],
      dtype='object')

In [51]:
import sys
!{sys.executable} -m pip install mysql-connector-python

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels
Collecting mysql-connector-python
  Downloading mysql_connector_python-26.7.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (11 kB)
Downloading mysql_connector_python-26.7.0-cp312-cp312-manylinux_2_28_x86_64.whl (21.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.7/21.7 MB 11.2 MB/s  0:00:01eta 0:00:01
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-26.7.0

In [53]:
import sqlite3

In [54]:
conn = sqlite3.connect("walmart_analysis.db")
df.to_sql("walmart_sales", conn, if_exists="replace", index=False)
https://www.anaconda.com/pricing
cursor = conn.cursor()
cursor.execute("SELECT COUNT(*) FROM walmart_sales;")
print(cursor.fetchone())

(9969,)

In [56]:
host = "mysql-xxxxx.aivencloud.com"
port = 12345
user = "avnadmin"
password = "generated_password"
database = "defaultdb"

In [57]:
df.to_csv("walmart_cleaned.csv", index=False)

In [58]:
check = pd.read_csv("walmart_cleaned.csv")
check.head()
check.shape

(9969, 12)